### ISSUE TITLE
minion problem

### ISSUE THREAD

**Issue by zettabyte918** [m-byte918/MultiOgarII#1512]
###  minion count as a real player!
![Capture](https://user-images.githubusercontent.com/18426424/61992779-d480b880-b062-11e9-9313-4214ac1cf37b.PNG)

**Comment by Agarian** [comment]
Is it really? I honestly doubt it would take all that much from server performance, as my MultiOgar server (albeit long abandoned, over in agarian-2) filters bots from players.

**Comment by zettabyte918** [comment]
thats how you do it 
![Capture](https://user-images.githubusercontent.com/18426424/65985690-96e54500-e482-11e9-86c6-7aed26243651.PNG)
