### ISSUE TITLE
How to add hotkeys?

### ISSUE THREAD

**Issue by chernxbyl42069** [m-byte918/MultiOgarII#1521]
Could someone just help me to understand where I can add hotkeys? I really can't figure out how.. and I know this is a client sided problem, but if anyone knows it would be greatly appreciated if someone could let me know...

**Comment by Tombez** [comment]
Which client are you wanting to add 'hotkeys' to?

**Comment by Cabotrez** [comment]
@Tombez Cigar2

**Comment by Tombez** [comment]
https://github.com/Cigar2/Cigar2/blob/d3fa09fe2e9bf6c216b899c989381698329b6890/web/assets/js/main_out.js#L1598
Put an if statement checking if `key` is equal to the key you want to do something when it's pressed.
Inside the if statement, write code to do what you want to happen when that key is pressed.
