### ISSUE TITLE
Disconnected

### ISSUE THREAD

**Issue by KittyTigerWolf** [m-byte918/MultiOgarII#1522]
Normal installation on Mac OS X Mojave
Server seems to run fine in the console except one error message: 
> [Error] Failed to start stats server: listen EADDRINUSE: address already in use :::88

When I try to join the server in agar.io though, a "Disconnected" text comes up.
I have tried different ports as well as just localhost, but none of them work.
Help would be appreciated.

**Comment by HiiZun** [comment]
this port is already used

**Comment by KittyTigerWolf** [comment]
How do I fix this problem then, so that I can connect. Changing the port doesn't help, the error goes away, yes, but I still can't connect to it.

**Comment by Tombez** [comment]
Have you tried 127.0.0.1:port instead of localhost:port?

**Comment by KittyTigerWolf** [comment]
Yes, I am using 127.0.0.1:port, also there are no errors when connecting, but there are a few warnings, here are all the console messages
![image](https://user-images.githubusercontent.com/38829336/66712799-9ca42a00-eda2-11e9-9715-d9f0daecca5f.png)

**Comment by FirstCodeReviewer** [comment]
Find out which service is running on your specific port and terminate it, if you don't need it.
`lsof -i :port`

**Comment by Borys64** [comment]
@KittyTigerWolf Are you connecting to port `88`?

**Comment by demostanis-worlds** [comment]
`kill $(lsof -i:88)`
Note: you should change to another unused port, as port 88 is used by [kerberos](https://en.wikipedia.org/wiki/List_of_TCP_and_UDP_port_numbers)

**Comment by Tombez** [comment]
I believe MultiOgarII does not currently work with agar.io. You may need to use an open source client such as [Cigar](https://github.com/Luka967/Cigar) or [Cigar2](https://github.com/Cigar2/Cigar2).

**Comment by Borys64** [comment]
Guys 88 is the stat port, its a system reserved port and therefore requires root permits. 8080 is the server port, so unless you're using the stats for something, you don't really need it.
