### ISSUE TITLE
Speed in config.js doesn't do anything

### ISSUE THREAD

**Issue by Dragonshadow14** [m-byte918/MultiOgarII#1530]
i cant get the speed config to work no matter what i set it to its always slow.

**Comment by poposita** [comment]
in playerCell.js change the getSpeed() function fot this
```
getSpeed(dist) {
        var speed = 2.2 * Math.pow(this._size, -0.439);
        speed *= 40 * this.server.config.playerSpeed;
        return Math.min(dist, speed) / dist;
    };
```

**Comment by Dragonshadow14** [comment]
> in playerCell.js change the getSpeed() function fot this
> 
> ```
> getSpeed(dist) {
>         var speed = 2.2 * Math.pow(this._size, -0.439);
>         speed *= 40 * this.server.config.playerSpeed;
>         return Math.min(dist, speed) / dist;
>     };
> ```

Thanks! this worked. someone should really fix it.
