### ISSUE TITLE
Cannot read property 's' of undefined, not connecting

### ISSUE THREAD

**Issue by coloran** [m-byte918/MultiOgarII#1531]
I tried using both MultiOgar-Edited and OgarII versions, but there would appear the same error when I try to connect to the private server. https://prnt.sc/q3x7w9
**"Cannot read property 's' of undefined."** what does that even mean I never saw someone else get the same error (it also happens when I casually enter agar.io to play with friends, the Inspect tab is flooded with these error things) I have properly installed node.js and the only problem here is this.
What are these: https://prnt.sc/q3xaxf and is there any fix? (also this link is when i normally open agario without servers)

**Comment by coloran** [comment]
Also this second link is

**Comment by Borys64** [comment]
Support for the official agar.io client hasn't been revised since mid last year, please use Cigar or a client alike.
