### ISSUE TITLE
Error message when joining

### ISSUE THREAD

**Issue by MiffedLyric559** [m-byte918/MultiOgarII#1532]
When trying to join with core.disableIntegrityChecks(true); core.connect("ws://127.0.0.1:8090");

I get this in the logs
[NONE ][16:50:51] CONNECTED 127.0.0.1:52497, origin: "https://agar.io"
[NONE ][16:51:02] DISCONNECTED 127.0.0.1:52497, code: 1009, reason: "Spam", name: ""

Also this shows up in the console of the browser:

Connecting to arena...
VM3598:1 GET https://securepubads.g.doubleclick.net/gampad/ads?gdfp_req=1&pvsid=1083293386281909&correlator=354565958572043&output=ldjh&impl=fifs&vrg=2019111801&guci=1.2.0.0.2.2.0.0&plat=1%3A536903688%2C2%3A536903688%2C8%3A32776&sc=1&sfv=1-0-36&ecs=20191202&iu_parts=116850162%2C300x250_login%2C728x90_login%2CAgar.io_160x600_Left_MainMenu%2CAgar.io_160x600_Right_MainMenu&enc_prev_ius=%2F0%2F1%2C%2F0%2F2%2C%2F0%2F3%2C%2F0%2F4&prev_iu_szs=300x250%2C728x90%2C160x600%2C160x600&eri=1&cust_params=abtest%3D0&cookie_enabled=1&bc=31&abxe=1&lmt=1575301865&dt=1575301865038&dlt=1575301767867&idt=3523&frm=20&biw=1153&bih=1009&oid=3&adxs=-12245933%2C-12245933%2C-12245933%2C-12245933&adys=-12245933%2C-12245933%2C-12245933%2C-12245933&adks=1234065766%2C2294042257%2C3800101096%2C904481605&ucis=5%7C6%7C7%7C8&ifi=2&u_tz=60&u_his=7&u_h=1080&u_w=1920&u_ah=1080&u_aw=1920&u_cd=24&u_nplug=3&u_nmime=4&u_sd=1&flash=0&url=https%3A%2F%2Fagar.io%2F%23ffa&dssz=48&icsg=211723678122224&std=0&vis=1&dmc=8&scr_x=0&scr_y=0&psz=0x-1%7C0x0%7C0x0%7C0x0&msz=0x-1%7C0x0%7C0x0%7C0x0&ga_vid=256243542.1575301776&ga_sid=1575301776&ga_hid=871512792&fws=132%2C132%2C132%2C132&ohw=1153%2C1153%2C1153%2C1153 net::ERR_BLOCKED_BY_CLIENT

**Comment by Borys64** [comment]
I recommend you use a client such as [Cigar](https://github.com/CigarProject/Cigar) as the official agar.io client is unsupported. 

As for the error you're experiencing i can only guess that you entered this into the console once the page has been loaded. As a result of this the `core.disableIntegrityChecks(false)` isn't registered. This makes the client send an integrity check to the server and as this message is too large, the server recognises it as spam and kicks the client.
