### ISSUE TITLE
cant conntect to multiogarII "WebSocket is closed before the connection is established" help fast

### ISSUE THREAD

**Issue by Dragonshadow14** [m-byte918/MultiOgarII#1535]
it used to work but now it doesnt. please help

**Comment by Tombez** [comment]
What client are you using?

**Comment by Dragonshadow14** [comment]
> What client are you using?

Cigar2

**Comment by Dragonshadow14** [comment]
I dont get why it wont work

**Comment by Tombez** [comment]
I can't reproduce the issue using the latest versions Cigar2 and MOII, maybe try updating them?

**Comment by Dragonshadow14** [comment]
> I can't reproduce the issue using the latest versions Cigar2 and MOII, maybe try updating them?
Now it's just saying ERR_CONNECTION_REFFUSED.
I dont know why. It worked last week

**Comment by Tombez** [comment]
Double check the port being used by MOII, and the port Cigar is trying to connect to.

**Comment by Dragonshadow14** [comment]
> Double check the port being used by MOII, and the port Cigar is trying to connect to.

MultiOgar is set to port 8080 and cigar is in port 8080. 
I have it port forwarded. 
I still cant connect.

**Comment by Dragonshadow14** [comment]
This fixed itself. I just tried connecting and out of nowhere I can connect. This is strange.

**Comment by barn-advisor** [comment]
i am experiencing this error too how strange
