### ISSUE TITLE
I wanna know how to achieve this things in multiogar

### ISSUE THREAD

**Issue by area111314** [m-byte918/MultiOgarII#1538]
Hello I recently played with my friends and this happened.
https://i.imgur.com/0wVu20u.png
I was wondering what could cause such things to be happened?
Since I was just spectating the player 1,and suddenly my view changed and i can see the whole map.

**Comment by Borys64** [comment]
This issue sometimes occurs when an incompatible client connects to the server, can you tell me what client you were using and what server version?

**Comment by Borys64** [comment]
This issue sometimes occurs when an incompatible client connects to the server, can you tell me what client you were using and what server version?

**Comment by area111314** [comment]
Sorry my bad. I found out that the sever side is using Cigar 2 not Multiogar.
