### ISSUE TITLE
Add Support For Secure Websocket

### ISSUE THREAD

**Issue by ZandercraftGames** [m-byte918/MultiOgarII#1542]
### Why is it needed?
Any client running on https (SSL), will not be able to connect to the MultiOgarII instance unless it runs over the wss:// protocol. This was originally in the gameserver.js file before changes were made to its name and were there since it's implementation in the original MultiOgar fork by Barbosik. 
### What happened to it?
It was originally committed here:
https://github.com/Barbosik/MultiOgar/commit/cf1c5dd1fe5024060df49e38b9447ce7105895a1
After that, I'm not sure when or why support was removed from your fork.
### What exactly is the error with connection?
As seen in the Javascript Developer Console on the website:
```
main_out.js:326 WebSocket connection to 'wss://<REDACTED>:441/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
```

**Comment by Borys64** [comment]
It was removed to decrease the size of the repository, I'll re-implement it however.

**Comment by Knyxishere** [comment]
Any update?

**Comment by Knyxishere** [comment]
I forgot: WebSocket connection to 'wss://127.0.0.1:myport/' failed: Error in connection establishment: net::ERR_SSL_PROTOCOL_ERROR that's the error chrome console throw.

**Comment by EzSnipes26** [comment]
> It was removed to decrease the size of the repository, however I'll re-implement it.

how to make it work

**Comment by Borys64** [comment]
Sorry I don't have enough time at the moment due to college, I'll try it next week.

**Comment by Borys64** [comment]
Added TLS support, you should now be able to use HTTPS. For instructions on how to do so, please take a look at the [README](https://github.com/m-byte918/MultiOgarII/blob/master/README.md#tls). 

I will leave this issue open just in case any vulnerabilities are found.

**Comment by Borys64** [comment]
@ZandercraftGames @Knyxishere @EzSnipes26 - Please ensure your local repo matches the public one. You can do this with `git pull`.

**Comment by EzSnipes26** [comment]
i have it updated and i use cloudflare for certification and key and i have them in the keys folder and it logs using https:// use the wss:// protocol while connecting but it dosent work still
