### ISSUE TITLE
Any know how to fix this

### ISSUE THREAD

**Issue by PranshuTG** [m-byte918/MultiOgarII#1546]
Err address unreachable

I'm using Ubuntu 20.14 
It worked the first time
And then never worked again

**Comment by Borys64** [comment]
Where is this error displayed? Within the nodejs output or a browser console?

**Comment by PranshuTG** [comment]
Browser

**Comment by Borys64** [comment]
That isn't an issue with the server, chances are you are inputting the wrong URL.

**Comment by PranshuTG** [comment]
It isn't I'm using my public ip:443
And I enabled port forwarding

It worked the first time and now isn't working

**Comment by Borys64** [comment]
Tell me what you're doing exactly. What client are you using and what prefix are you using with the server ip (`ws` or something else).

**Comment by PranshuTG** [comment]
@Borys64 I'm using using cigar client from agarian
And opening the chrome console it shows 
Connecting to public IP:443
ERR ADDRESS UNREACHABLE

**Comment by Tombez** [comment]
Connecting to your own public ip doesn't work, use the local ip of the computer that's hosting the server. If you're trying to connect with the same computer that is hosting, use `127.0.0.1:443` or `localhost:443`
