### ISSUE TITLE
how to add skins

### ISSUE THREAD

**Issue by AnUnnnamedUser** [m-byte918/MultiOgarII#1554]
how to add skins

**Comment by Tombez** [comment]
Skins are added to the client, not the server. If you want players to be able to pick a random skin by using the skin name `r`, then you must add the names of the skins on your client into `src/randomskins.txt`, separated by newlines.

**Comment by AnUnnnamedUser** [comment]
If you want players to be able to pick a random skin by using the skin name r, then you must add the names of the skins on your client into src/randomskins.txt, separated by newlines. i have made the secont thing if i spawn bots they dont have skins! only the name. where i have to put "r"
