### ISSUE TITLE
how to make that the bots have skins

### ISSUE THREAD

**Issue by AnUnnnamedUser** [m-byte918/MultiOgarII#1555]
my server runs at agario.fun and its not my client. so how to make that the bots have skins.  i readed this: _If you want players to be able to pick a random skin by using the skin name r, then you must add the names of the skins on your client into src/randomskins.txt_  i have already made "src/randomskins" but where i have to put "r"?

**Comment by Tombez** [comment]
You put the `r` between angle brackets in the bot's name. Such as `<r>Bot1`. Bot names are chosen randomly from `src/ai/botnames.txt`. Put the names that you want bots to have in that file, separated by newlines.

**Comment by AnUnnnamedUser** [comment]
@Tombez thanks! :)
