### ISSUE TITLE
Help make a freeze keybind

### ISSUE THREAD

**Issue by Phoenix132** [m-byte918/MultiOgarII#1572]
I recently started a multiogar project on glitch.com and I'm wondering if there is a way to make a freeze keybind, where it changes your movement speed to zero and disable colliding cells.

**Comment by Dramex** [comment]
i can make the server side pr for this, but the client already has many bind keys and i doubt the will add it

**Comment by Phoenix132** [comment]
ok

**Comment by Phoenix132** [comment]
> i can make the server side pr for this, but the client already has many bind keys and i doubt they will add it

Yea, I'm not expecting the devs to add it, I just want the code for it. I experimented with many different things, but they all gave me errors and undesired outcomes.

**Comment by Phoenix132** [comment]
:( anyone know how to make it???

**Comment by Phoenix132** [comment]
no one helped me so imma close this :/
