### ISSUE TITLE
making cells under a specific size instant recombine

### ISSUE THREAD

**Issue by xAentix** [m-byte918/MultiOgarII#1575]
not really a issue more of question because im trying to make so cells under 50 cell size instant recombine and i haven't been able to figure out myself so if anyone knows it would help out so much

**Comment by Phoenix3214** [comment]
You can make a flag variable????? So the condition is if cell size <= 50 then instant recombine????

**Comment by Phoenix3214** [comment]
idfk remember how to code it

**Comment by Tombez** [comment]
After [this line](https://github.com/m-byte918/MultiOgarII/blob/75409a68da009069b6a5b28e492e30eb0748e804/src/Server.js#L518) in Server.js, add `if (cell._mass < 50) time = 0;`
